fixced whitespace

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -51,11 +51,11 @@ git-tag-release:
 .PHONY: pull-translations
 if HAVE_RSYNC
 pull-translations:
-        $(RSYNC) -Lrtvz translationproject.org::tp/latest/libexif/ $(top_srcdir)/po
+	$(RSYNC) -Lrtvz translationproject.org::tp/latest/libexif/ $(top_srcdir)/po
 else
 pull-translations:
-        echo "Error: Cannot pull translations: Could not find rsync at configure time."
-        exit 1
+	echo "Error: Cannot pull translations: Could not find rsync at configure time."
+	exit 1
 endif
 
 
